version: '2.2'

services:
  url_shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - ./urls.txt:/app/urls.txt
      - ./config.ini:/app/config.ini
    restart: always
