services:
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    image: pavelveter/urlshortener:latest
    ports:
      - '8081:8081'
    volumes:
      - ./urls.txt:/app/urls.txt
      - ./config.ini:/app/config.ini
    restart: always
